[package]
name = "ransid"
description = "Rust ANSI Driver"
repository = "https://github.com/redox-os/ransid"
version = "0.1.1"
license-file = "LICENSE"
readme = "README.md"
keywords = ["redox", "ansi"]
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "ransid"
path = "src/lib.rs"
